# Generated by Django 6.1 on 2026-08-26 18:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('email', models.CharField(blank=True, max_length=150)),
                ('cnpj', models.CharField(blank=True, max_length=30)),
                ('especialidade', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('quantidade_estoque', models.PositiveIntegerField(default=0)),
                ('estoque_minimo', models.PositiveIntegerField(default=5)),
                ('preco_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_cadastro', models.DateField(default=django.utils.timezone.localdate)),
                ('data_ultima_entrada', models.DateField(blank=True, null=True)),
                ('quantidade_entrada', models.PositiveIntegerField(default=0)),
                ('unidade_medida', models.CharField(choices=[('unidade', 'Unidade'), ('caixa', 'Caixa'), ('pacote', 'Pacote'), ('kg', 'Kg'), ('litro', 'Litro')], default='unidade', max_length=20)),
                ('localizacao_estoque', models.CharField(blank=True, max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='estoque.categoria')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='estoque.fornecedor')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_venda', models.DateField(default=django.utils.timezone.localdate)),
                ('quantidade_vendida', models.PositiveIntegerField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('forma_pagamento', models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('Cartão de Débito', 'Cartão de Débito'), ('Cartão de Crédito', 'Cartão de Crédito'), ('Pix', 'Pix')], max_length=30)),
                ('vendedor', models.CharField(max_length=100)),
                ('cliente', models.CharField(blank=True, max_length=100)),
                ('nota_cliente', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='estoque.produto')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-data_venda', '-id'],
            },
        ),
    ]
